#Canvas due assignment

import keyboard
import time

keyboard.send('windows + s')
time.sleep(0.5)
keyboard.write('Google Chrome')
time.sleep(0.5)
keyboard.send('enter')
time.sleep(1)
keyboard.write('https://ucas-edu.instructure.com/calendar#view_name=week&view_start=2024-11-15')
time.sleep(0.5)
keyboard.send('enter')
time.sleep(0.5)
keyboard.send('ctrl + t')
time.sleep(0.5)
keyboard.write('https://ucas-edu.instructure.com/grades')
time.sleep(0.5)
keyboard.send('enter')
time.sleep(0.5)
keyboard.send('ctrl + tab')
time.sleep(0.5)
keyboard.send('f11')
time.sleep(0.8)
keyboard.send('windows + s')
time.sleep(0.5)
keyboard.write('terminal')
time.sleep(0.5)
keyboard.send('enter')
time.sleep(2)
keyboard.write('Setup correctly, enjoy :)')
time.sleep(1)
keyboard.send('alt + f4')